language: python

python:
    - "3.4"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update

install:
    - sudo apt-get install g++-4.8
    - sudo apt-get install libgtest-dev
    - sudo apt-get install python-numpy
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/local/lib/
    - cd -

script:
    - cd c++
    - make
    - make test
    - cd -
    - cd python
    - make test
