language: cpp

compiler:
    - gcc

before_install:
    # https://github.com/beark/ftl/blob/master/.travis.yml
    - sudo apt-get update
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
    - sudo apt-get install g++-4.8

script:
    - cd c++
    - make
    - make test
