language: cpp

compiler:
    - gcc

before_install:
    # https://github.com/beark/ftl/blob/master/.travis.yml
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update

install:
    - sudo apt-get install g++-4.8
    - sudo apt-get install doxygen
    - sudo apt-get install libtest-dev
    - sudo apt-get install valgrind
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/local/lib/
    - cd -

script:
    - cd c++
    - make
    - make test
