language: python

python:
    - "3.4"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update

install:
	- uname
    - pip install --upgrade pip
    - pip install coverage
    - sudo apt-get install g++-4.8
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/local/lib/
    - cd -
    - sudo apt-get install python-numpy
    - sudo apt-get install valgrind

script:
    - cd c++
    - make test
    - cd -
    - cd python
    - make test
