all:

clean:
	rm -f  *.pyc
	rm -rf __pycache__

test:
	./BinarySearch2.py
	./BinarySearch3.py
	./GCD.py
	./GCD2.py
	./IsPrime2.py
	./LowerBound.py
	./LowerBound2.py
	./LowerBound3.py
	./Sieve2.py
	./Sieve4.py
